export { createShape2D, getShape2DDisplayName } from './create2DShapes'
export type { Shape2DType, Shape2DParams } from './create2DShapes'
export { createPlane } from './createPlane'
export { createCube } from './createCube'
export { createSphere } from './createSphere'
export { createCylinder } from './createCylinder'
export { createCone } from './createCone'
export { createTorus } from './createTorus'
export { createCapsule } from './createCapsule'
export type { PlaneParams } from './createPlane'
export type { CubeParams } from './createCube'
export type { SphereParams } from './createSphere'
export type { CylinderParams } from './createCylinder'
export type { ConeParams } from './createCone'
export type { TorusParams } from './createTorus'
export type { CapsuleParams } from './createCapsule'
export { generate3D, defaultParams3D, PRIMITIVE_3D_REGISTRY, CATEGORIES_3D, CATEGORY_LABELS_3D, TYPES_BY_CATEGORY_3D, QUICK_ACCESS_3D } from './registry3D'
export type { Primitive3DType, Category3D, Prim3DConfig, Field3D } from './registry3D'
